# Generated by Django 3.2.3 on 2021-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.EmailField(max_length=100)),
                ("recovery_question", models.CharField(max_length=100)),
                ("recovery_answer", models.CharField(max_length=100)),
            ],
        ),
    ]
