# Generated by Django 3.2.3 on 2021-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=50)),
                ("kind", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("cover_url", models.CharField(max_length=250)),
                ("rating", models.FloatField(null=True)),
                ("genres", models.JSONField(null=True)),
                ("directors", models.JSONField(null=True)),
                ("synopsis", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
